/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const CustomOrder = IDL.Record({
  'customerName' : IDL.Text,
  'orderDetails' : IDL.Text,
  'email' : IDL.Text,
  'timestamp' : Time,
  'contactNo' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'inStock' : IDL.Bool,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'rating' : IDL.Float64,
  'price' : IDL.Int,
  'reviewCount' : IDL.Nat,
});
export const CartItem = IDL.Record({
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
});
export const Cart = IDL.Record({
  'user' : IDL.Principal,
  'items' : IDL.Vec(CartItem),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearCart' : IDL.Func([], [], []),
  'getAllCustomOrders' : IDL.Func([], [IDL.Vec(CustomOrder)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllProductsByPrice' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllProductsByRating' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [Cart], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeFromCart' : IDL.Func([IDL.Nat], [], []),
  'submitCustomOrder' : IDL.Func([CustomOrder], [IDL.Text], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const CustomOrder = IDL.Record({
    'customerName' : IDL.Text,
    'orderDetails' : IDL.Text,
    'email' : IDL.Text,
    'timestamp' : Time,
    'contactNo' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'inStock' : IDL.Bool,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'rating' : IDL.Float64,
    'price' : IDL.Int,
    'reviewCount' : IDL.Nat,
  });
  const CartItem = IDL.Record({ 'productId' : IDL.Nat, 'quantity' : IDL.Nat });
  const Cart = IDL.Record({
    'user' : IDL.Principal,
    'items' : IDL.Vec(CartItem),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addToCart' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearCart' : IDL.Func([], [], []),
    'getAllCustomOrders' : IDL.Func([], [IDL.Vec(CustomOrder)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllProductsByPrice' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllProductsByRating' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [Cart], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeFromCart' : IDL.Func([IDL.Nat], [], []),
    'submitCustomOrder' : IDL.Func([CustomOrder], [IDL.Text], []),
  });
};

export const init = ({ IDL }) => { return []; };